### ISSUE TITLE
Cannot import CircleTimerView

### ISSUE THREAD

**Issue by gaiabeatrice** [jiahuanyu/CircleTimerView#3]
Hi, we can't import CircleTimerView as there's no instruction about the importing in the gradle.

**Comment by jiahuanyu** [comment]
yeahp, i did not make it as a libary that can import in gradle. But, you can import the CircleTimerView by download project and copy the java file into your project, there is only one java file, called 'CircleTimerView' in library folder, u need to copy.

**Comment by jiahuanyu** [comment]
i am glad to do public this library by jitpack :)
