### ISSUE TITLE
Timer running on background

### ISSUE THREAD

**Issue by fedmeloni** [jiahuanyu/CircleTimerView#4]
Hi, 
when I change activity and I go back to TimerActivity the timer doesn't keep record of previous time. How can I make it work in background?

**Comment by jiahuanyu** [comment]
i think, you finish the TimerActivity and go to another activity. If you do that, you should recode the status of the timer, include current time and whether it is working now. When you back to the TimerActivity, you see whether there is a record, and restore the status of the timer.  I hope it is helpful for u
